Cambios a rutas para habilitar altimetria
fabianabarca/buses pull request #89
Opened 2021-10-26 22:34 UTC by Herquila

Pull request para contribuir los cambios para altimetria.

2021-10-28 04:12 UTC, jeancahu requested changes
Hola ya lo ejecuté y lo probé localmente y está excelente, lo que sí no sé es como obtuvo los datos de alt sería genial aportar eso también, para la próxima te recomiendo trabajar sobre stable que es una versión sin cosas quebradas de main, main es un poco más caótico por alguna razón, pero stable está actualizado.
Ahí te dejo un par de recomendaciones, sus commits ya están meged a stable pero podemos seguir usando este PR para perfeccionar aún más la sección.
Como sugerencia vamos a tratar de sacar de static las cosas del proyecto para que no estén revueltas con vendor entonces ese elevationChart.js y demás JS puede ir en rutas/static/rutas/ y a la hora de importarlo se usa {% static 'static/rutas/elevationChart.js' %} o algo así, por ahí va, no está listo aún y todavía hay cosas ahí pero a la larga esa es la intención.

2021-11-02 04:51 UTC, Herquila commented on buses/rutas/models.py
> +    shape = models.CharField(
Hola, si, Si no me equivoco, este cambio fue a peticion de Fabian durante una de las sesiones, no recuerdo bien el problema que presento.

2021-11-02 04:52 UTC, Herquila commented on buses/rutas/models.py
> +    pt_alt = models.DecimalField(
Entendido, voy a documentar el script que hice y lo voy a agregar.

2021-11-02 04:53 UTC, Herquila commented on buses/rutas/views.py
> +import os
Entendido, tal vez fue un remanente de algun intento anterior que se me olvido limpiar

2021-11-02 04:55 UTC, Herquila commented on buses/rutas/urls.py
> +    path('<url_ruta>/', views.altimetria, name='altimetria'),
Entendido

2021-11-02 17:38 UTC, jeancahu commented on buses/rutas/models.py
> +    shape = models.CharField(
Entiendo las razones por las cuales @fabianabarca podría haber contemplado este patch, el problema con el _ForeingKey_ es que si el _Shape_ no existe como tal entonces va a fallar durante la creación del _Trip_, pero entonces en este caso podríamos dedicar un poco más de tiempo a desarrollar una solución para que no nos de problemas a futuro, ya que lo que pasa con el _CharField_ es que va a permitir que el _Trip_ tenga _Shapes_ que no necesariamente existan en base de datos.

El admin que tenga que definir el _Shape_ de un _Trip_ en la página de Admin tendrá que introducirlo como texto y esto da entrada a errores humanos en los cuales el ID no sea exactamente igual al del _Shape_ que la persona espera vincular al _Trip_.

A la hora de crear los _Trips_ se necesita que ya existan los _Shapes_ es por esto que si se introducen los _Shapes_ primero a DB y luego los _Trips_ no habría problema, pero al hacerlo en el orden contrario si habría, otra manera sería:

```python
try:
  createTrip(id, ..., ..., shape_id='myshape')

except NoExisteElShape:
  createShape("myshape")
  createTrip(id, ..., ..., shape_id='myshape')
```

Afortunadamente yo creo que **Django** tiene métodos ya propios por lo que no se requeriría verificar con el _try_
por ejemplo el _ForeignKey_ permite valores nulos () en la columna así como valores vacíos ("")

```python
    shape = models.ForeignKey(
        'Shape', null=True, blank=True, on_delete=models.SET_NULL,
```

Lo que habría que hacer es que cuando se creé un _Trip_ y el _Shape_ al cual hace referencia el _ForeingKey_ **no exista** en lugar de que el programa falle y se detenga la ejecución o no se creé el _Trip_ hay que aplicar alguna de  las siguientes opciones:

1. Ignorar el Shape ID colocado en la creación del _Trip_ y colocar un valor _Null_ en la columna
2. Crear el _Shape_ al cual se hace referencia, vacío por el momento o con un valor _default_.

Es posible que _ForeignKey_ o alguna otra estructura de Django permita crear este objeto cuando se requiera y no esté en DB a partir de un valor por defecto para el _Shape_, lo que quedaría por hacer una vez ya se quiera definir bien el _Shape_ sería actualizar sus valores internos.

Esperemos a ver que dice @fabianabarca al respecto para ver que podemos hacer con esto.

2022-10-23 01:48 UTC, closed without merging